name: CI

on:
  pull_request:
    branches: ["*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run ruff
        run: poetry run ruff check .

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run mypy
        run: poetry run mypy --strict code_coil

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=code_coil --cov-fail-under=80

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Test install
        run: |
          python -m pip install .

  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          check-external-urls: 'true'

  front-matter-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Validate Front Matter Schema
        uses: hashicorp/front-matter-schema@v1.0.0
        with:
          path: 'content'
          schema: |-
            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "title": "CodeCoil Q&A Entry Front Matter Schema",
              "description": "Schema for validating front matter in CodeCoil Markdown files",
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "Unique identifier for the entry"
                },
                "domain": {
                  "type": "string",
                  "description": "The broad category of the entry"
                },
                "topic": {
                  "type": "string",
                  "description": "The specific topic within the domain"
                },
                "subtopic": {
                  "type": "string",
                  "description": "The subtopic within the topic"
                },
                "difficulty": {
                  "type": "string",
                  "description": "The difficulty level of the entry",
                  "enum": ["easy", "medium", "hard"]
                },
                "keywords": {
                  "type": "array",
                  "description": "A list of relevant keywords for the entry",
                  "items": {
                    "type": "string"
                  },
                  "minItems": 1,
                  "uniqueItems": true
                }
              },
              "required": ["id", "domain", "topic", "subtopic", "difficulty", "keywords"]
            }

  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          check-external-urls: 'true'
